
harvest:

  baseUrl: https://localhost:8282/
  headers:
  # TODO put me in CI as env variable, should not be committed
    accountId: 690203
    authorization: 1506753.pt.2Q_O1jc_mDMZKnlM9-R37Ej1LQIF90ZLFNJoP1SvUtTZRUtypcq3YkkhFZdwjxWqPsE0HrDa2G8sakbeJghemA

  oauth2:
    clientID: dummy-client-id
    clientSecret: dummy-client-secret
    accessTokenUri: https://localhost:8282/o/oauth2/token
    userAuthorizationUri: https://localhost:8282/o/oauth2/v2/harvestauth
    redirectUri: http://localhost:8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    ch.aaap.harvestclient: DEBUG
    ch.aaap.admin: DEBUG
    # to debug HTTP requests
    # ch.aaap.harvestclient.core.Harvest.http: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: dummy-client-id
            client-secret: dummy-client-secret
            client-name: 3APAdmin
            scope: profile #scope: profile openid email
            redirectUriTemplate: http://localhost:8080/login/oauth2/code/google
          github-client-1:
            client-id: f1262e4d24a1665155fa
            client-secret: 9479ce803914ff5bbccfa69450c763d89a9eff4e
            client-name: Github user
            provider: github
            scope: user
            redirect_uri: http://localhost:8080/oauth2/authorize/code/github  
        provider: 
          google: 
            tokenUri: https://localhost:8282/o/oauth2/token
            authorizationUri: https://localhost:8282/o/oauth2/v2/auth
            userInfoUri: https://localhost:8282/oauth2/v3/userinfo
  application:
    name: user-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:3apadmin
    driver-class-name: org.h2.Driver
    username: sa
    password: null
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
