## Image where we run the e2e_tests when on circleCI
# currently pushed at docker hub under vladandj/openjdk8-self-signed-cert-jks-node-browsers:0.0.1

#circleci/openjdk:8-node-browsers

FROM vladandj/openjdk8-self-signed-cert-jks-node-browsers:0.0.3

USER root

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

COPY ./cert/selfsigned.crt /etc/ssl/certs/

# cypress dependencies
RUN sudo apt-get update && \
  sudo apt-get install -y \
    libgtk2.0-0 \
    libnotify-dev \
    libgconf-2-4 \
    libnss3 \
    libxss1 \
    libasound2 \
    xvfb
	
#import cert into jks
RUN sudo keytool -import -alias node-server-self-signed-cert -file /etc/ssl/certs/selfsigned.crt -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit -noprompt
RUN keytool -list -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit -noprompt

# versions of local tools
RUN node -v
RUN npm -v
