spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    appname: eureka-server
    preferIpAddress: true
    status-page-url-path: /info
    health-check-url-path: /health
  client:
    service-url:
      defaultZone: http://3apadmin-eureka-server.scapp.io
